const CartActionTypes = {
  ADD_ITEM: "ADD_ITEM",
  REMOVE_ITEM: "REMOVE_ITEM",
  CLEAR_ITEM_FROM_CART: "CLEAR_ITEM_FROM_CART",
  CART_EMPTY: "CART_EMPTY",
  CART_SAVE_SHIPPING_ADDRESS: "CART_SAVE_SHIPPING_ADDRESS",
  CART_EDIT_SHIPPING_ADDRESS: "CART_EDIT_SHIPPING_ADDRESS",
  CLEAR_ITEM_SHIPPINGADDRESS: "CLEAR_ITEM_SHIPPINGADDRESS",
};

export default CartActionTypes;
