export const SAVE_MAIN_QUERY = "SAVE_MAIN_QUERY";
export const SAVE_SEARCH_FILTERQUERY = "SAVE_SEARCH_FILTERQUERY";
export const SAVE_COLLECTIONS = "SAVE_COLLECTIONS";
export const SAVE_FILTERED = "SAVE_FILTERED";
export const COLLECTION_FETCH_LOADNIG = "COLLECTION_FETCH_LOADNIG";
export const CATSUB_FETCH_LOADNIG = "CATSUB_FETCH_LOADNIG";
export const FETCH_CAT_SUB_WITH_FILTERKEY = "FETCH_CAT_SUB_WITH_FILTERKEY";
export const CLEAR_ALL_FILTERS = "CLEAR_ALL_FILTERS";
